// AUTO-GENERATED by scripts/import-schedule.mjs — do not edit manually
import type { DayPlan } from '../types/dayPlan';

const day1Plan: DayPlan = {
  "day": 1,
  "title": "抵釜・西面安頓",
  "subtitle": "金海機場入境 → 輕軌換乘 → 西面飯店 → 晚間散策",
  "tags": [
    "路程",
    "住宿",
    "購物"
  ],
  "timeline": [
    {
      "time": "15:30",
      "event": "KE 2086 抵達金海機場",
      "dotColor": "accent"
    },
    {
      "time": "15:30–16:30",
      "event": "入境・領行李・換匯",
      "dotColor": "accent"
    },
    {
      "time": "16:30–17:15",
      "event": "輕軌→沙上→地鐵→西面",
      "dotColor": "teal"
    },
    {
      "time": "17:15–17:30",
      "event": "Urbanstay Seomyeon 入住",
      "dotColor": "gold"
    },
    {
      "time": "18:30–21:00",
      "event": "田浦＋西面雜貨散策",
      "dotColor": "blue"
    }
  ],
  "sections": [
    {
      "num": "01",
      "title": "抵達金海機場・入境手續",
      "timeRange": "15:30–16:00",
      "mapQuery": "김해국제공항",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "teal",
          "rows": [
            {
              "label": "航班",
              "value": "KE 2086 大韓航空"
            },
            {
              "label": "抵達",
              "value": "15:30 釜山金海國際機場 (PUS)"
            },
            {
              "label": "入境時間",
              "value": "約 30–50 分鐘"
            }
          ]
        },
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "accent",
              "label": "1",
              "title": "入境審查（Immigration）",
              "body": "持台灣護照走「外國人」通道。可使用自動通關或人工審查。",
              "alerts": [
                {
                  "variant": "note",
                  "text": "需事先完成 Q-Code 健康聲明（出發 48 小時內填寫）。"
                }
              ],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "2",
              "title": "領取行李",
              "body": "確認航班行李轉盤號碼，國際線到達大廳 1F 領取。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "gold",
              "label": "3",
              "title": "換匯（建議）",
              "body": "出關後至 **1F Money Box 換錢所**（黃色招牌）換取韓元，匯率優於市區銀行。",
              "alerts": [
                {
                  "variant": "tip",
                  "text": "建議備妥 ₩200,000 現金作為頭兩天零用。"
                }
              ],
              "tickets": [],
              "photoRefs": []
            }
          ]
        },
        {
          "kind": "photo-ref",
          "label": "機場參考資訊",
          "desc": "出關路線・換匯・交通步驟圖解",
          "links": [
            {
              "text": "→ 出機場路線・輕軌搭乘步驟圖解",
              "href": "https://debbiechien.com/busan-gimhae-airport-transportation/",
              "style": "teal"
            },
            {
              "text": "→ Money Box 換錢全攻略",
              "href": "https://lizzzstyle.tw/money-box-gimhae/",
              "style": "default"
            }
          ]
        }
      ]
    },
    {
      "num": "10",
      "title": "行前 Checklist",
      "timeRange": "",
      "mapQuery": "",
      "blocks": [
        {
          "kind": "checklist",
          "items": [
            "護照（效期 6 個月以上）",
            "信用卡 / 金融卡（建議帶 Visa）",
            "韓國 10 日 SIM 卡或 eSIM",
            "備妥現金 ₩200,000",
            "填寫 Q-Code（出發前 48 小時內）",
            "下載 Naver Map 離線地圖（釜山市區）",
            "行動電源（隨身行李）",
            "220V 雙圓孔轉接頭"
          ]
        }
      ]
    }
  ]
};

export default day1Plan;
