// AUTO-GENERATED by scripts/import-schedule.mjs — do not edit manually
import type { DayPlan } from '../types/dayPlan';

const day4Plan: DayPlan = {
  "day": 4,
  "title": "東釜山奢華一日",
  "subtitle": "OPS早餐 → Skyline Luge 斜坡滑車 → 尾浦站搭天空膠囊列車 → 青沙浦午餐烤扇貝 → Spa Land 汗蒸幕 → 廣安里晚餐",
  "tags": [
    "Pass 紫色 ×2（Luge + Spa Land）",
    "膠囊列車需提前預約",
    "海岸列車 Pass 免費",
    "東釜山精華串聯"
  ],
  "timeline": [
    { "time": "08:00", "event": "OPS 烘焙坊早餐", "dotColor": "gold" },
    { "time": "09:30", "event": "Skyline Luge 斜坡滑車", "dotColor": "accent" },
    { "time": "11:30", "event": "天空膠囊列車（尾浦→青沙浦）", "dotColor": "blue" },
    { "time": "12:30", "event": "青沙浦午餐（烤扇貝/咖啡廳）", "dotColor": "teal" },
    { "time": "14:30", "event": "Spa Land 新世界汗蒸幕", "dotColor": "accent" },
    { "time": "18:30", "event": "廣安里晚餐", "dotColor": "accent" }
  ],
  "sections": [
    {
      "num": "01",
      "title": "早餐：OPS 烘焙坊",
      "timeRange": "08:00–09:00",
      "mapQuery": "옵스해운대점",
      "blocks": [
        {
          "kind": "alert",
          "variant": "tip",
          "text": "OPS 烘焙坊為海雲台人氣早餐店，08:00 開門。平日通常不用太久，早點到就好。"
        },
        {
          "kind": "info-card",
          "variant": "gold",
          "rows": [
            {
              "label": "步行",
              "value": "從 Ramada Encore 出發：沿海雲台海濱路步行約 8–10 分鐘可達。"
            },
            {
              "label": "叫車韓文／地址",
              "value": "(옵스해운대점)"
            },
            {
              "label": "時間",
              "value": "08:00 開門，早到最好"
            },
            {
              "label": "推薦",
              "value": "招牌生乳包、可頌、三明治；2人點 2–3 樣輕食即可"
            }
          ]
        },
        {
          "kind": "photo-ref",
          "label": "OPS 烘焙坊 · 海雲台早餐",
          "desc": "必點品項、排隊狀況、周邊早餐選擇",
          "links": [
            { "text": "→ OPS 烘焙坊攻略（中文）", "href": "https://www.google.com/search?q=OPS+烘焙坊+海雲台+攻略+中文", "style": "default" }
          ]
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "早餐後帶著飽足感出發，今天路程遠（機張），要早點去才能避開人潮。"
        }
      ]
    },
    {
      "num": "02",
      "title": "前往東釜山 Skyline Luge → 斜坡滑車（2 次）",
      "timeRange": "09:00 出發｜09:30–11:00 停留約 90 分鐘",
      "mapQuery": "스카이라인 루지 부산",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "accent",
          "rows": [
            {
              "label": "叫車韓文／地址",
              "value": "(스카이라인 루지 부산)　或　(부산 기장군 기장읍 기장해안로 205)　｜　東釜山 Osiria 觀光園區，靠近釜山樂天世界"
            },
            {
              "label": "交通",
              "value": "海雲台飯店 → Skyline Luge，計程車約 **30–40 分鐘、₩20,000–25,000**。是全天唯一一段較遠的計程車程，必搭。"
            },
            {
              "label": "另一選項",
              "value": "從釜山站搭 1001 號公車到「龍宮寺/國立水產科學研究所」站下車步行 5 分鐘，但來回超過 3 小時，不建議。"
            },
            {
              "label": "門票",
              "value": "現場成人 2 次 ₩28,000；Pass 免費換 2 次（價值 ₩28,000）"
            },
            {
              "label": "預約",
              "value": "無需預約，現場到售票窗口出示 Pass 直接換票"
            },
            {
              "label": "每次",
              "value": "搭空中纜椅上山 + 斜坡滑車下來，約 15–20 分鐘"
            },
            {
              "label": "賽道",
              "value": "4 條路線（紅/藍/黃/橘），依當日開放；2 人可互相追逐"
            },
            {
              "label": "禁止",
              "value": "孕婦、高血壓、心臟病、椎間盤突出者不可搭乘；85cm 以下不可搭"
            }
          ]
        },
        {
          "kind": "ticket",
          "text": "海雲台飯店 → Skyline Luge ｜ 計程車 ≈ ₩23,000 ｜ 約 35 分"
        },
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "accent",
              "label": "①",
              "title": "到售票窗口出示 Pass 換票",
              "body": "說「釜山通行證（Visit Busan Pass），2 次斜坡滑車（Luge 2 times）」即可換到 QR code 票券。\n換票後先選好頭盔尺寸（可自備拋棄式浴帽墊著戴，更衛生）。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "accent",
              "label": "②",
              "title": "搭空中纜椅（Skyride）上山",
              "body": "開放式四人座吊椅，慢速上山，可看到遠方釜山樂天世界城堡。上山時拍照順手。\n第一次工作人員會給你安全說明，認真聽！主要就是：手柄往後推加速、往前拉煞車，下坡時保持距離。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "accent",
              "label": "③",
              "title": "第一次滑行：走新手路線",
              "body": "在山頂上坐上滑車，跟著指示出發。兩人可以一前一後互相追逐超車，有競速感。滑行過程**禁止拿出手機拍攝**，定點攝影機會自動拍，結束後可在照片區查看並購買。\n一圈約 15–20 分鐘，含等待纜椅。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "accent",
              "label": "④",
              "title": "第二次滑行：挑刺激路線",
              "body": "再搭纜椅上山，第二次選更刺激的路線（如紅色路線）。這次不用重聽教學，直接出發，可以更放開飆速！\n若覺得 2 次不夠過癮，可現場加購 1 次 ₩12,000（約 NT$265），以 Pass 節省了主費用後，加購非常划算。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "warn",
          "text": "手柄要握穩，煞車要提前。彎道多，第一次一定要慢慢來感受，等第二次再飆速。「手很酸」是普遍心得，請有心理準備。"
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "結束後安全帽先別急著還！走到照片挑選區，感應手環或票券就會跳出你滑行中的定格照，覺得好的話可以購買留念（₩10,000–15,000）。"
        },
        {
          "kind": "photo-ref",
          "label": "空中纜椅視角・滑車俯衝・Pass 換票流程",
          "desc": "纜椅上看樂天世界全景、換票流程、賽道俯瞰、定點攝影照選購",
          "links": [
            { "text": "→ Debbie｜Pass換票+搭乘全流程", "href": "https://debbiechien.com/busan-skyline-luge/", "style": "default" },
            { "text": "→ 喵爸｜2km賽道心得+照片", "href": "https://kimiyo.tw/busan-skyline-luge/", "style": "red" },
            { "text": "→ BISH｜超值評價+纜椅俯瞰照", "href": "https://bishdream.com/skyline-luge-busan/", "style": "amber" },
            { "text": "→ 蔡小妞｜2次體驗影片紀錄", "href": "https://tsnio.com/busan-skyline-luge/", "style": "teal" }
          ]
        }
      ]
    },
    {
      "num": "03",
      "title": "Skyline Luge → 尾浦站 → 天空膠囊列車（尾浦 → 青沙浦）",
      "timeRange": "11:00 出發｜11:30–12:20 搭乘",
      "mapQuery": "해운대블루라인파크 미포역",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "blue",
          "rows": [
            {
              "label": "交通",
              "value": "Skyline Luge 出口搭計程車，目的地：**海雲台藍線公園 尾浦站** (해운대블루라인파크 미포역)"
            },
            {
              "label": "費用",
              "value": "約 **₩15,000–20,000、20–25 分鐘**。沿途公車站就在入口前，但計程車省時。"
            },
            {
              "label": "目的",
              "value": "在 11:30 的預約時段前 10 分鐘抵達尾浦站，上二樓搭乘天空膠囊列車。"
            }
          ]
        },
        {
          "kind": "ticket",
          "text": "Skyline Luge 出口 → 尾浦站 ｜ 計程車 ≈ ₩17,000 ｜ 約 22 分"
        },
        {
          "kind": "alert",
          "variant": "warn",
          "text": "膠囊列車是預約時段制（如 11:30–12:00），**必須在時段內抵達**，建議提早 10 分鐘到站排隊。時段過了就無法搭乘！"
        },
        {
          "kind": "info-card",
          "variant": "blue",
          "rows": [
            {
              "label": "路線",
              "value": "尾浦站 → 青沙浦站，靠海外側，單程約 30 分鐘"
            },
            {
              "label": "票價",
              "value": "2人座單程 **₩40,000**（2024/12 漲價後），即 2 人共用一張票"
            },
            {
              "label": "預約",
              "value": "必須提前線上預約！官網英文版或 Trip.com。每週二開放往後 4 週票。"
            },
            {
              "label": "注意",
              "value": "Pass 只含海岸列車（免費），天空膠囊列車不含在 Pass 內，需另外付費"
            },
            {
              "label": "換票",
              "value": "尾浦站 1F 自動售票機或人工窗台，掃描預訂 QR code 即可換票"
            },
            {
              "label": "入口",
              "value": "膠囊列車在 2F，海岸列車在 1F，入口不同勿走錯"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "**乘車體驗重點：**尾浦出發的去程走**靠海外側**，海景視野完全無遮蔽，是拍照的黃金方向。車廂最多坐 4 人，2 人獨享一個車廂是最浪漫的！時速僅 5km/h，超緩慢，讓你有充裕時間邊搖晃邊拍照。往後看可以看到廣安大橋橫跨海面，往前則是湛藍無邊海景。"
        },
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "blue",
              "label": "①",
              "title": "到 1F 自動售票機換票",
              "body": "掃描預訂 QR code 換取實體票券。機台有中文介面，不難操作。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "blue",
              "label": "②",
              "title": "上 2F 排隊候車",
              "body": "工作人員會依序安排上車，通常 2 人就獨享一台車廂。\n上車後可開窗通風（夏天建議開），也可以**連接藍牙喇叭**播自己的背景音樂，超加分。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "blue",
              "label": "③",
              "title": "青沙浦站下車 → 拍灌籃高手平交道",
              "body": "到站後先別急著去吃飯，出站後往鐵軌平交道方向走，就是網紅「釜山版灌籃高手平交道」，拍攝角度：站在平交道正中，遠方就是湛藍海天一線。\n**注意安全！**雖然列車速度很慢，但仍要注意有無車輛通過。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "note",
          "text": "膠囊列車官網：**blueline.haundaebluelinepark.com**（選 English 版，選 Mipo 出發，Sky Capsule，2人座單程）。Trip.com 購票也可以，且免到官網兌票，直接掃碼入場。"
        },
        {
          "kind": "alert",
          "variant": "warn",
          "text": "天空膠囊列車有不定期定期檢查停駛（通常每年 11 月），出發前請至官網確認當天有正常運營。"
        },
        {
          "kind": "photo-ref",
          "label": "膠囊列車車廂內部・海景・灌籃高手平交道",
          "desc": "車廂內拍海景最佳角度、尾浦站外觀換票機台、灌籃高手平交道拍攝位置",
          "links": [
            { "text": "→ 樂活大方｜官網預約圖解教學", "href": "https://www.bigfang.tw/blog/post/bluelinepark-busan", "style": "default" },
            { "text": "→ Debbie｜尾浦出發全攻略", "href": "https://debbiechien.com/bluelinepark-sky-capsule-beach-train/", "style": "red" },
            { "text": "→ 蔡小妞｜3次搭乘心得比較", "href": "https://tsnio.com/haeundae-blueline-park/", "style": "amber" },
            { "text": "→ Liz｜Trip.com訂票不兌換教學", "href": "https://lizzzstyle.tw/sky-capsule/", "style": "teal" }
          ]
        }
      ]
    },
    {
      "num": "04",
      "title": "青沙浦中場：三種方案依當下狀態選擇",
      "timeRange": "12:30–14:00",
      "blocks": [
        {
          "kind": "alert",
          "variant": "note",
          "text": "玩完 Luge + 膠囊列車，到達青沙浦時約 12:30。**依當下肚子感覺選擇方案**，不用強迫自己吃正餐。Spa Land 內也有拉麵和點心，所以青沙浦這裡輕食或跳過都完全沒問題。"
        },
        {
          "kind": "info-card",
          "variant": "teal",
          "rows": [
            {
              "label": "方案 A",
              "value": "**炭火烤扇貝正餐**（肚子餓・想吃海鮮）— 秀敏家 (수민이네) 推薦：炭火烤法鮮甜、Local 風格、菜單有中文。烤蛤蠣什錦中份 ₩40,000–50,000 + 拉麵或鮑魚粥共享一碗 ₩12,000–15,000。**絕對不要點套餐！**最便宜的套餐也要 ₩150,000 起。直接點單品，2人吃飽約 ₩50,000–65,000 就夠。\n**Naver / Google Map：수민이네 청사포**"
            },
            {
              "label": "方案 B",
              "value": "**青沙浦海景咖啡廳輕食**（不太餓・想坐著看海補能量）— Cheongsa Foret (청사포레) 推薦：屋頂咖啡廳，可同時拍到紅白燈塔＋膠囊列車＋平交道，可頌鬆餅＋咖啡約 ₩18,000–22,000 / 2人。\n**Naver / Google Map：청사포레**"
            },
            {
              "label": "方案 C",
              "value": "**直接前往 Spa Land，館內解決**（完全不餓・想早點泡湯）— 拍完平交道直接叫車出發，館內自助拉麵區（₩10,000/人）解決，吃拉麵可延長停留至 6 小時。"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "**怎麼選？一句話判斷：**\n「下膠囊列車時肚子餓了」→ 方案 A（正餐 ₩55,000–65,000，約 1 小時）\n「小餓想坐著看海歇腳」→ 方案 B（輕食 ₩20,000–25,000，約 30–40 分鐘）\n「不餓，只想快點泡湯」→ 方案 C（直達 Spa Land，館內吃 ₩10,000/人）"
        },
        {
          "kind": "photo-ref",
          "label": "烤扇貝澎湃擺盤・屋頂海景・可頌鬆餅・燈塔拍攝角度",
          "desc": "秀敏家烤扇貝攻略、Cheongsa Foret 屋頂攻略、Broni 乳酪蛋糕",
          "links": [
            { "text": "→ 秀敏家攻略", "href": "https://www.bigfang.tw/blog/post/cheongsapo-suminine-busan", "style": "default" },
            { "text": "→ 道熙家攻略", "href": "https://debbiechien.com/dohee-nae/", "style": "default" },
            { "text": "→ Cheongsa Foret 屋頂攻略", "href": "https://lifebank.tw/chengsaporet/", "style": "amber" },
            { "text": "→ Broni 乳酪蛋糕", "href": "https://lizzzstyle.tw/broni/", "style": "teal" }
          ]
        }
      ]
    },
    {
      "num": "05",
      "title": "海岸列車（Pass 免費）",
      "timeRange": "青沙浦 → 尾浦段",
      "mapQuery": "해운대블루라인파크 청사포역",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "blue",
          "rows": [
            {
              "label": "Pass",
              "value": "海岸列車全程 **Pass 免費**（Visit Busan Pass），持 Pass 直接上車，無需另行購票"
            },
            {
              "label": "路線",
              "value": "青沙浦站 → 달맞이고개역 → 尾浦站（미포역），沿海雲台海岸線行駛"
            },
            {
              "label": "班次",
              "value": "約每 30 分鐘一班，單程約 20 分鐘"
            },
            {
              "label": "入口",
              "value": "青沙浦站 1F（從天空膠囊列車 2F 下樓後右轉即達）"
            },
            {
              "label": "體驗",
              "value": "靠海外側景色最好，可欣賞海雲台海岸線全景，是輕鬆的沿海觀光體驗"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "Pass 持有者搭海岸列車完全免費，是從青沙浦前往尾浦轉乘的最佳方式，邊欣賞海景邊移動，不趕時間的話強烈推薦。"
        }
      ]
    },
    {
      "num": "06",
      "title": "青沙浦 → Centum City（Spa Land）",
      "timeRange": "14:00–14:30",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "blue",
          "rows": [
            {
              "label": "方案 A（海岸列車 Pass 免費）",
              "value": "在青沙浦站 1F 搭乘海岸列車，Pass 免費，沿海岸行駛至尾浦站（약 20분）。尾浦站下車後，步行或叫車至海雲台站，再搭地鐵 2 號線至 Centum City 站（₩1,400/人）。"
            },
            {
              "label": "方案 B（計程車直達）",
              "value": "**計程車直達（效率優先）**：青沙浦 → 新世界百貨 Centum City，約 **₩9,000–12,000、15 分鐘**。午餐後直接出發，效率最高。"
            }
          ]
        },
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "blue",
              "label": "①",
              "title": "青沙浦站 1F 搭乘海岸列車",
              "body": "從青沙浦膠囊列車站 2F 下樓，在 1F 月台出示 Pass 免費搭乘海岸列車。靠海外側座位視野最佳。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "blue",
              "label": "②",
              "title": "海岸列車沿線（青沙浦 → 達迷路 → 尾浦）",
              "body": "共 3 站，約 20 分鐘，沿途海岸景色壯觀。到**尾浦站（미포역）**下車。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "blue",
              "label": "③",
              "title": "尾浦站轉乘 → Centum City",
              "body": "尾浦站下車後，步行前往**海雲台站（해운대역）**（約 10 分鐘），搭地鐵 2 號線往 서면 方向，至 **Centum City 站（센텀시티역）**下車。\n地鐵票 ₩1,400/人。或在尾浦直接叫計程車到新世界百貨（約 ₩8,000–10,000）。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            }
          ]
        },
        {
          "kind": "ticket",
          "text": "青沙浦 → 新世界百貨 Centum City ｜ 計程車 ≈ ₩10,000 ｜ 約 15 分"
        }
      ]
    },
    {
      "num": "07",
      "title": "Spa Land 新世界汗蒸幕",
      "timeRange": "14:30–18:30｜最長4小時",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "accent",
          "rows": [
            {
              "label": "地址",
              "value": "新世界百貨 Centum City 店 1F（Dior 旁通道）"
            },
            {
              "label": "交通",
              "value": "地鐵 2 號線 Centum City 站 12 號出口，步行 1 分鐘"
            },
            {
              "label": "時間",
              "value": "平日淡季 09:00–22:00（最後入場 21:00）"
            },
            {
              "label": "門票",
              "value": "成人 ₩23,000（平日）；持 Pass 免費入場 4 小時"
            },
            {
              "label": "Pass",
              "value": "在入口出示 Visit Busan Pass，免費換票"
            },
            {
              "label": "時限",
              "value": "入場含 4 小時；場內消費 ₩10,000 以上可延長至 6 小時"
            }
          ]
        },
        {
          "kind": "checklist",
          "items": [
            "出示 Pass 換票 → 脫鞋放鞋櫃 → 領取晶片手環 → 男女分開更衣淋浴 → 換汗蒸服 → 汗蒸幕 × 溫泉泡湯 → 公共休息區 → 泡麵吃到飽區 → 沖澡 → 結帳離場"
          ]
        },
        {
          "kind": "info-card",
          "variant": "accent",
          "rows": [
            {
              "label": "設施亮點",
              "value": "18 種溫泉池 + 13 種主題汗蒸幕（黃土房、鹽房、玉石房、芬蘭桑拿、羅馬式…），男女分開泡湯區，男女合用公共汗蒸幕大廳。"
            },
            {
              "label": "必體驗",
              "value": "**配料吃到飽拉麵區**：點基本拉麵（₩10,000），花枝、起司、年糕、豆芽等配料自助加！幾乎人人必吃，靠這個可延長停留至 6 小時。"
            },
            {
              "label": "帶去的",
              "value": "一套備用內衣褲（泡湯後換上），簡單梳洗用品（現場有提供基本的），浴帽（自備，戴安全帽時有用到）。"
            },
            {
              "label": "注意",
              "value": "全館禁帶外食、禁菸、溫泉區更衣室**嚴禁錄影拍照**（手機要收起來！）；公共汗蒸幕區可以拍照。"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "建議體驗順序：①先泡湯（男女分開大浴場） → ②換汗蒸服進公共區 → ③輪流進各種汗蒸房（從低溫到高溫） → ④在休息區發呆睡覺 → ⑤吃泡麵 → ⑥再泡足湯 → ⑦最後沖澡梳洗準備晚餐。"
        },
        {
          "kind": "alert",
          "variant": "warn",
          "text": "消費全靠手環紀錄，離場前務必到「出場結帳台」刷手環結清，再插回鞋櫃取鞋。忘記結帳的話出不去！"
        },
        {
          "kind": "photo-ref",
          "label": "Spa Land 內部・汗蒸房・泡麵區・流程圖解",
          "desc": "公共大廳汗蒸幕主題區照片、配料拉麵實拍、入場換票流程、更衣室結構說明",
          "links": [
            { "text": "→ Debbie｜超詳細流程+必玩設施", "href": "https://debbiechien.com/spa-land-centum-city-busan/", "style": "default" },
            { "text": "→ MAMAHUHU｜更衣室圖解+行李寄放", "href": "https://mamahuhu.blog/overseas/spa-land-centum-city/", "style": "default" },
            { "text": "→ 喵爸｜五星設備完整評測", "href": "https://kimiyo.tw/spa-land/", "style": "amber" },
            { "text": "→ Kiara｜配料泡麵區+體驗心得", "href": "https://kiara.tw/spa-land/", "style": "teal" }
          ]
        }
      ]
    },
    {
      "num": "08",
      "title": "晚餐：廣安里烤肉",
      "timeRange": "18:30 起",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "accent",
          "rows": [
            {
              "label": "交通",
              "value": "Centum City 站搭地鐵 2 號線，往廣安里方向（Marine City 或廣安站），約 10–15 分鐘。"
            },
            {
              "label": "選項 A",
              "value": "**李河貞醬蟹** (이하정간장게장)（廣安里附近）｜生醃醬蟹，韓國米飯小偷美食，夠吃 2 人份 ₩60,000–80,000。先查 Naver 評分確認還在。"
            },
            {
              "label": "選項 B",
              "value": "**廣安里燒烤街**｜廣安里海邊附近有很多烤肉店，烤完散步到海邊看廣安大橋燈光，完美收尾。"
            },
            {
              "label": "選項 C",
              "value": "如果 Spa Land 泡到飽懶得走遠，**新世界百貨內**本身就有不少餐廳，直接在百貨內解決也很方便。"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "note",
          "text": "Spa Land 泡完會整個人放空懶洋洋，晚餐選近一點、不用等太久的地方。廣安里搭地鐵 2 站就到，或Centum City 站附近直接找都行。"
        }
      ]
    },
    {
      "num": "09",
      "title": "Day 4 費用試算（2人）",
      "timeRange": "",
      "blocks": [
        {
          "kind": "menu",
          "header": "費用明細",
          "items": [
            { "name": "OPS 早餐（2人）", "note": "₩20,000 — 輕食各一份" },
            { "name": "計程車 海雲台→Skyline Luge", "note": "₩23,000 — 約 35 分" },
            { "name": "Skyline Luge（2人×2次）", "note": "₩0 — Pass 免費（省 ₩56,000）" },
            { "name": "計程車 Skyline Luge→尾浦站", "note": "₩17,000 — 約 22 分" },
            { "name": "天空膠囊列車（2人座單程）", "note": "₩40,000 — 非 Pass 項目，需另行付費" },
            { "name": "計程車 青沙浦→Centum City", "note": "₩10,000 — 約 15 分" },
            { "name": "青沙浦中場（方案A 烤扇貝）", "note": "₩55,000 — 烤貝中份+拉麵（肚子餓選這）" },
            { "name": "方案B 咖啡廳輕食（替代）", "note": "₩22,000 — 點心+飲料（省 ₩33,000）" },
            { "name": "方案C Spa Land館內（替代）", "note": "₩20,000 — 館內拉麵×2（省 ₩35,000）" },
            { "name": "Spa Land（2人）", "note": "₩0 — Pass 免費（省 ₩46,000）" },
            { "name": "Spa Land 泡麵（各一碗）", "note": "₩20,000 — 配料吃到飽，場內消費" },
            { "name": "地鐵 Centum City → 廣安里", "note": "₩2,800 — 2人 ×₩1,400" },
            { "name": "晚餐（2人）", "note": "₩70,000 — 烤肉或醬蟹" },
            { "name": "合計（以方案A為基準）", "note": "≈ ₩257,800 — 方案B省₩33,000；方案C省₩35,000" }
          ]
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "Day 4 的 Pass 使用效益最高：Luge ₩56,000 + Spa Land ₩46,000，合計省 **₩102,000（約 NT$2,260）**，今天一天就回本大半張 BIG5 Pass！"
        }
      ]
    },
    {
      "num": "10",
      "title": "Day 4 行前 Checklist",
      "timeRange": "",
      "blocks": [
        {
          "kind": "checklist",
          "items": [
            "**出發前（訂票）**：天空膠囊列車 Trip.com 或官網訂票，選尾浦出發，時段 11:30–12:00，2人座單程 ₩40,000。",
            "**Pass 確認**：Day 4 要用紫色景點 ×2（Luge + Spa Land），確認還有足夠使用次數。",
            "**Visit Busan Pass 剩餘確認**：Day 4 使用紫色景點 2 個：Skyline Luge（₩28,000）+ Spa Land（₩23,000），合計省 ₩51,000。",
            "**自備浴帽**：戴頭盔時隔絕公用安全帽，Spa Land 也有用（非必要但貼心）。",
            "**帶備用內衣褲**：Spa Land 泡完後換上的，讓身體更舒爽。",
            "**Skyline Luge 地址**：提前存入叫車 App，韓文：(부산 기장군 기장읍 기장해안로 205)",
            "**膠囊列車時段**：**必須在預約時段內抵達！**計程車提前10分鐘叫車確保準時。",
            "**青沙浦平交道**：從膠囊列車青沙浦站出來，先拍灌籃高手平交道（出站後左轉），再去吃午餐。",
            "**Spa Land 手環**：入場領到手環後好好保管，場內所有消費都靠它刷。離場前到出場台結帳。",
            "**晚餐方向**：泡完 Spa Land 後懶懶的，就在 Centum City 附近吃，或搭 2 站地鐵去廣安里。"
          ]
        }
      ]
    }
  ]
};

export default day4Plan;
