// AUTO-GENERATED by scripts/import-schedule.mjs — do not edit manually
import type { DayPlan } from '../types/dayPlan';

const day2Plan: DayPlan = {
  "day": 2,
  "title": "全日玩水・水上樂園日",
  "subtitle": "西面 → 金海樂天水上樂園 → 西面飯店（原路返回）",
  "tags": [
    "計程車去回",
    "車程各 35–40 分",
    "車資各 ₩20,000–25,000",
    "10:00 開園"
  ],
  "timeline": [
    {
      "time": "08:00",
      "event": "早餐：飯店樓下或西面便利商店解決",
      "dotColor": "muted"
    },
    {
      "time": "08:30",
      "event": "打開 Kakao T 叫計程車出發",
      "dotColor": "accent"
    },
    {
      "time": "09:10",
      "event": "抵達金海樂天水上樂園・換票・更衣・儲值手環",
      "dotColor": "accent"
    },
    {
      "time": "10:00",
      "event": "開園！衝熱門設施（Giant Boomerang、Tornado Slide）",
      "dotColor": "accent"
    },
    {
      "time": "12:30",
      "event": "園內午餐（手環刷卡消費）",
      "dotColor": "muted"
    },
    {
      "time": "13:30",
      "event": "午後繼續玩：懶人河、室內波浪池、SPA區放鬆",
      "dotColor": "accent"
    },
    {
      "time": "16:00",
      "event": "更衣吹乾・退手環押金・準備離園",
      "dotColor": "accent"
    },
    {
      "time": "16:30",
      "event": "園門口叫計程車回西面",
      "dotColor": "accent"
    },
    {
      "time": "17:15",
      "event": "回飯店梳洗休息",
      "dotColor": "muted"
    },
    {
      "time": "19:00",
      "event": "晚餐：西面烤肉（味贊王 或 烤肉的男子）",
      "dotColor": "muted"
    },
    {
      "time": "21:00",
      "event": "早睡養精蓄銳，明天 Day 3 行程最重",
      "dotColor": "muted"
    }
  ],
  "sections": [
    {
      "num": "01",
      "title": "早餐・出發前準備",
      "timeRange": "07:30–08:30",
      "mapQuery": "",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "amber",
          "rows": [
            {
              "label": "早餐",
              "value": "今天全日玩水，體力消耗大，務必好好吃早餐。飯店旁的 **CU / GS25 / emart24** 便利商店即可解決：飯糰＋三角壽司＋熱美式，快速方便。"
            },
            {
              "label": "行前裝備",
              "value": "泳衣（身上穿或夾鏈袋裝）、毛巾（水上樂園可租，但自帶更省錢）、夾腳拖或水鞋、防曬乳、防水手機袋（重要！手環付款期間手機要能拿出來）、換洗衣物＋護膚品（玩完要舒服出門吃晚餐）。"
            },
            {
              "label": "現金",
              "value": "手環儲值後園內大多刷手環，但建議帶 ₩30,000–50,000 現金備用（計程車、手環押金等）。"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "warn",
          "text": "⚠ **禁帶物品：**外食、玻璃瓶、大型充氣水上器材（1m以上）、寵物、嬰兒車。水上樂園入場前會有**隨機行李檢查**，零食可帶密封容器水果、寶特瓶飲料，但外食便當絕對不行。"
        }
      ]
    },
    {
      "num": "02",
      "title": "交通：西面 → 金海樂天水上樂園",
      "timeRange": "08:30 出發｜車程 35–40 分鐘",
      "mapQuery": "롯데워터파크 김해",
      "blocks": [
        {
          "kind": "highlight",
          "title": "💡 為什麼搭計程車，不搭大眾運輸？",
          "body": "水上樂園位於金海市長有路，離釜山市區有段距離。公車需在輕軌府院站（502）轉搭，加上等候時間約 60–70 分鐘，且今天帶泳裝毛巾行李，計程車兩人分攤每人約 ₩10,000–12,500（約 NT$220–280），划算又快。"
        },
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "blue",
              "label": "①",
              "title": "用 Kakao T App 叫車（建議出門前 10 分鐘叫）",
              "body": "打開 **Kakao T**（韓國最大叫車平台），設定出發地為飯店、目的地輸入 **「롯데워터파크 김해」**（金海樂天水上樂園）。\n選一般車（일반택시）即可，費用預估會顯示在畫面上，信用卡付款或現金均可。",
              "alerts": [
                {
                  "variant": "note",
                  "text": "ℹ Kakao T 也支援英文介面，在設定切換語言即可。韓國計程車多為瓦斯車（LPG），後車廂空間比一般油車略小，帶大包包的話提前告知司機或選較大車型。"
                }
              ],
              "tickets": [],
              "photoRefs": [
                {
                  "label": "Kakao T 叫車教學",
                  "desc": "App 介面操作、如何輸入目的地韓文、付款方式設定",
                  "links": [
                    {
                      "text": "→ Debbie｜叫車流程說明",
                      "href": "https://debbiechien.com/busan-gimhae-airport-transportation/",
                      "style": "default"
                    },
                    {
                      "text": "→ PanPan｜計程車費用試算",
                      "href": "https://panpanlife.com/busan-arrival/",
                      "style": "default"
                    }
                  ]
                }
              ]
            },
            {
              "dotColor": "blue",
              "label": "②",
              "title": "車程與費用",
              "body": "西面出發，走金海方向，全程不塞車約 **35–40 分鐘**，含高速路段。\n費用約 **₩20,000–25,000**，若走高速公路需加 ₩2,000–3,000 路費，司機會自動走最快路線。",
              "alerts": [],
              "tickets": [
                {
                  "text": "西面 → 金海樂天水上樂園 ｜ 車程 35–40 分鐘 ｜ 費用 ₩20,000–25,000"
                }
              ],
              "photoRefs": []
            },
            {
              "dotColor": "blue",
              "label": "③",
              "title": "抵達・入口確認",
              "body": "地址：**경상남도 김해시 장유로 555**（慶尚南道金海市長有路555）。告訴司機「롯데워터파크」（樂天水上樂園）即可，司機都知道。\n抵達後，在入口處下車，進去前先找到**換票處**兌換已預購的 KKday / Klook 票券（掃 QR Code 即可入場）。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            }
          ]
        }
      ]
    },
    {
      "num": "03",
      "title": "門票・購票",
      "timeRange": "",
      "mapQuery": "",
      "blocks": [
        {
          "kind": "alert",
          "variant": "tip",
          "text": "💡 請出發前在 **KKday** 或 **Klook** 預購全日票（約 ₩32,000/人），到場掃 QR Code 直接入場，省去現場排隊購票時間。詳細準備事項見「Day 2 行前 Checklist」。"
        }
      ]
    },
    {
      "num": "04",
      "title": "入場流程・手環儲值・置物",
      "timeRange": "09:10–10:00",
      "mapQuery": "",
      "blocks": [
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "teal",
              "label": "①",
              "title": "入場驗票",
              "body": "在入口掃 QR Code 後，工作人員會在手腕綁上**橡皮筋手環**（這是入場識別，全天不能取下）。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "②",
              "title": "領取付款手環（RF 手環）・繳押金",
              "body": "入場後到服務台領取**無線感應付款手環（RF 팔찌）**，這個手環用來在園內刷卡消費：餐廳、租毛巾、附加項目等均刷此手環。\n需**繳交押金約 ₩10,000**，離場時退還（沒有消費到的餘額也退）。建議儲值 ₩30,000–50,000 在手環裡，一天午餐＋小點心＋租借項目大致夠用。",
              "alerts": [
                {
                  "variant": "warn",
                  "text": "⚠ 手環押金需現金繳交，記得帶 ₩10,000–20,000 現金備用。手環一定要帶好，離場前退還時會核對。"
                }
              ],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "③",
              "title": "更衣室・置物櫃",
              "body": "入場後先找更衣室換泳衣。置物櫃以手環感應鎖/開，全天可重複開關，**不需另外付費**（包含在入場費內）。\n手機、現金、換洗衣物、防曬乳等均存入置物櫃，只帶防水手機袋裝手機出去玩。",
              "alerts": [
                {
                  "variant": "tip",
                  "text": "💡 開園前（09:30–10:00 之間）先搶置物櫃，越靠近水區的置物櫃越搶手，人潮多的旺季建議早點到。"
                }
              ],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "④",
              "title": "領取毛巾（選擇自帶或租借）",
              "body": "若未自帶毛巾，可現場刷手環租借，費用約 ₩3,000–5,000。自帶一條大浴巾最划算也最舒適。\n救生圈/浮具也可租用或自備（長度不超過 1m）。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            }
          ]
        },
        {
          "kind": "photo-ref",
          "label": "水上樂園入場流程・手環・設施外觀",
          "desc": "入口外觀、手環樣式、置物櫃使用方式、更衣室照片",
          "links": [
            {
              "text": "→ Klook｜金海樂天水上樂園票券說明",
              "href": "https://www.klook.com/zh-TW/activity/88947-lotte-waterpark-pass-gimhae/",
              "style": "default"
            },
            {
              "text": "→ KKday｜門票含注意事項說明",
              "href": "https://www.kkday.com/zh-tw/product/104822",
              "style": "blue"
            },
            {
              "text": "→ HK01｜三大水上樂園攻略（含金海）",
              "href": "https://www.hk01.com/%E6%97%85%E9%81%8A/189751",
              "style": "amber"
            }
          ]
        }
      ]
    },
    {
      "num": "05",
      "title": "必玩設施攻略",
      "timeRange": "開園 10:00 衝刺",
      "mapQuery": "",
      "blocks": [
        {
          "kind": "highlight",
          "title": "🎯 開園策略",
          "body": "開園前 10 分鐘到閘口等候，開園後立刻先衝 Giant Boomerang 和 Tornado Slide，這兩個是排隊最長的設施，開園初期人最少。之後再回頭玩其他設施，下午人潮稍退再泡 SPA。"
        },
        {
          "kind": "facility-grid",
          "items": [
            {
              "name": "Giant Boomerang 자이언트 부메랑고",
              "tags": [
                {
                  "label": "★ 必玩",
                  "type": "must"
                },
                {
                  "label": "超刺激",
                  "type": "thrill"
                }
              ],
              "note": "國內最大 6 人用迴旋滑梯，開放式軌道高速衝下再急速上衝，腎上腺素爆表。開園必衝，人少時排隊僅 10–20 分鐘，旺季可達 60 分鐘。"
            },
            {
              "name": "Tornado Slide 토네이도 슬라이드",
              "tags": [
                {
                  "label": "★ 必玩",
                  "type": "must"
                },
                {
                  "label": "超刺激",
                  "type": "thrill"
                }
              ],
              "note": "龍捲風造型超大滑梯，坐橡皮艇急速衝入漩渦，超有速度感。人氣設施之一，也是開園先搶。"
            },
            {
              "name": "Racing Slide 레이싱 슬라이드",
              "tags": [
                {
                  "label": "刺激",
                  "type": "thrill"
                }
              ],
              "note": "多人並排競速滑梯，趴著衝下來比速度，很有趣。可以跟另一半比賽，節奏輕快不需等待太久。"
            },
            {
              "name": "Water Coaster 워터 코스터",
              "tags": [
                {
                  "label": "刺激",
                  "type": "thrill"
                }
              ],
              "note": "水上雲霄飛車型設施，坐車廂在水道上起伏衝浪，水陸結合的新體驗，強烈推薦嘗試。"
            },
            {
              "name": "室內波浪池 실내 파도풀",
              "tags": [
                {
                  "label": "輕鬆",
                  "type": "relax"
                }
              ],
              "note": "四季皆可玩的室內造浪池，浪高可達 1m 以上，夏天熱了可以進室內涼快一下，也很好玩。"
            },
            {
              "name": "懶人河 래피드 리버",
              "tags": [
                {
                  "label": "休閒",
                  "type": "relax"
                }
              ],
              "note": "坐橡皮圈沿著水道漂流，很適合玩累了中場休息，可以邊漂邊曬太陽放鬆，非常舒服。"
            },
            {
              "name": "Giant Volcano 자이언트 볼케이노",
              "tags": [
                {
                  "label": "刺激",
                  "type": "thrill"
                }
              ],
              "note": "38m高、35m寬的巨型火山，戶外波浪從中湧出，是整個樂園的地標。在旁邊感受海浪也很過癮。"
            },
            {
              "name": "SPA 溫泉區 스파풀",
              "tags": [
                {
                  "label": "放鬆",
                  "type": "relax"
                }
              ],
              "note": "溫熱水按摩池，下午 3 點後人少，特別適合玩累了泡一泡舒緩肌肉。SPA 區營業至 20:00，比戶外設施晚關閉。"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "note",
          "text": "ℹ **室內 vs 戶外：**室內區（파도풀、스파풀、室內滑梯）全年開放；戶外區（Giant Boomerang、Tornado Slide 等）依季節及天氣開放，夏季旺季全部開放。若遇陰天戶外設施仍多半運作，大雨才會暫停。"
        },
        {
          "kind": "photo-ref",
          "label": "設施實拍・水上樂園全景",
          "desc": "Giant Boomerang、Tornado Slide、懶人河、室內波浪池、SPA 區實拍，以及整個樂園鳥瞰",
          "links": [
            {
              "text": "→ 樂天官網｜設施介紹（含圖）",
              "href": "https://www.lotteresort.com/main/ko/theme-park/lotte-water-park?bizCd=91&urlLang=ko",
              "style": "default"
            },
            {
              "text": "→ Klook｜設施照片集",
              "href": "https://www.klook.com/zh-TW/activity/88947-lotte-waterpark-pass-gimhae/",
              "style": "blue"
            },
            {
              "text": "→ 金海市官方｜水上樂園介紹照片",
              "href": "https://www.gimhae.go.kr/00204/03060/03723.web?amode=view&idx=312",
              "style": "amber"
            }
          ]
        }
      ]
    },
    {
      "num": "06",
      "title": "建議遊玩順序（效率最高版）",
      "timeRange": "",
      "mapQuery": "",
      "blocks": [
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "teal",
              "label": "1",
              "title": "10:00 開園 → 立刻衝 Giant Boomerang",
              "body": "開園排隊最短的黃金 30 分鐘，先搶熱門，不排長龍。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "2",
              "title": "10:30 Tornado Slide → Racing Slide",
              "body": "趁人潮還少連玩兩個刺激設施。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "3",
              "title": "11:30 Water Coaster → 懶人河休息",
              "body": "刺激後用懶人河放鬆，順帶曬曬太陽消磨中午前時光。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "gray",
              "label": "4",
              "title": "12:30 午餐",
              "body": "刷手環在園內餐廳用餐，避開尖峰時段（11:30–13:00 最擠），稍等到 12:30 再去比較順。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "5",
              "title": "13:30 室內波浪池 → Giant Volcano 旁感受浪",
              "body": "下午室外人潮稍多，室內波浪池反而空一些。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "6",
              "title": "14:30 回玩熱門設施第二輪（若想再刷）",
              "body": "下午 2–3 點是一般玩完的人開始離場的時段，熱門設施隊伍會縮短。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "7",
              "title": "15:30 SPA 溫泉區泡泡・放鬆",
              "body": "玩一整天，最後用 SPA 收尾，全身舒緩一下再出發。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "blue",
              "label": "8",
              "title": "16:00 更衣・退手環・準備離園",
              "body": "吹乾頭髮（更衣室有吹風機），手環押金退回，整理好出發。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            }
          ]
        }
      ]
    },
    {
      "num": "07",
      "title": "園內午餐",
      "timeRange": "約 12:30–13:20",
      "mapQuery": "",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "teal",
          "rows": [
            {
              "label": "付款",
              "value": "全部刷**手環**，不需拿出錢包，非常方便。"
            },
            {
              "label": "選項",
              "value": "園內有多家餐廳和小吃攤，韓式炒飯、拉麵、炸雞、烤肉飯等，也有便利的自助式小食區。"
            },
            {
              "label": "價位",
              "value": "韓國水上樂園餐廳普遍定價偏高，一餐約 ₩12,000–18,000/人，**食量不大建議各點一份主食＋分食小點心**。"
            }
          ]
        },
        {
          "kind": "menu",
          "header": "午餐建議點法（食量小版）",
          "items": [
            {
              "name": "海鮮炒飯 해물볶음밥 或 石鍋拌飯 돌솥비빔밥",
              "note": "各點一份"
            },
            {
              "name": "炸雞 치킨 小份分食",
              "note": "體力消耗大，補充蛋白質"
            },
            {
              "name": "運動飲料 / 碳酸飲料",
              "note": "消耗大補充電解質"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "warn",
          "text": "⚠ 水上樂園禁止外帶食物入場，若想省餐費可帶密封容器裝去籽水果（如葡萄、草莓）或寶特瓶飲料進去，這是允許的。"
        }
      ]
    },
    {
      "num": "08",
      "title": "回程交通：水上樂園 → 西面",
      "timeRange": "16:30 出發",
      "mapQuery": "",
      "blocks": [
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "blue",
              "label": "①",
              "title": "在園門口叫計程車（Kakao T）",
              "body": "離園後在**正門口外**打開 Kakao T，設定目的地為西面飯店名稱或地址。\n若 Kakao T 在此處難叫，也可詢問門口工作人員或在停車場外攔計程車。",
              "alerts": [
                {
                  "variant": "note",
                  "text": "ℹ 下午 16:00–18:00 是許多人離園的時段，計程車需求高，建議**在換衣服時就用 App 預約叫車**，換好衣服出門計程車差不多也到了。"
                }
              ],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "blue",
              "label": "②",
              "title": "回程費用與時間",
              "body": "回程同樣約 **₩20,000–25,000**，35–40 分鐘，下午可能稍微遇到路況。",
              "alerts": [],
              "tickets": [
                {
                  "text": "金海水上樂園 → 西面 ｜ 車程 35–40 分 ｜ 費用 ₩20,000–25,000"
                }
              ],
              "photoRefs": []
            }
          ]
        }
      ]
    },
    {
      "num": "09",
      "title": "晚餐：味贊王鹽烤肉（西面）",
      "timeRange": "19:00–21:00",
      "mapQuery": "맛찬들왕소금구이 서면점",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "red",
          "rows": [
            {
              "label": "店名",
              "value": "**味贊王鹽烤肉** 맛찬들왕소금구이 서면점"
            },
            {
              "label": "位置",
              "value": "西面站步行約 5 分鐘"
            },
            {
              "label": "特色",
              "value": "14 天熟成豬肉、**專人桌邊烤服務**，豬頸肉（목살）最推薦"
            },
            {
              "label": "注意",
              "value": "旺季有排隊，建議 18:30 後稍避尖峰或現場等位"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "note",
          "text": "ℹ **備選｜烤肉的男子** 고기굽는남자 서면점 桌邊代烤、點餐附贈螃蟹海鮮湯，可用 Naver 事先預約。若味贊王排隊太久，直接換這間。"
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "💡 玩了一天水消耗大，晚餐可以大方點。豬頸肉（목살）或五花肉（삼겹살）各一份＋生啤酒一杯，就是完美的一天收尾。兩個人點 2 份肉＋各一碗白飯即可。"
        },
        {
          "kind": "photo-ref",
          "label": "烤肉餐廳外觀・菜單・桌邊烤肉服務",
          "desc": "味贊王店內環境、桌邊烤服務、豬頸肉照片；烤肉的男子螃蟹湯",
          "links": [
            {
              "text": "→ Debbie｜味贊王實拍＋評價",
              "href": "https://debbiechien.com/busan-restaurant-seomyeon/",
              "style": "default"
            },
            {
              "text": "→ 小菲｜烤肉的男子西面店介紹",
              "href": "https://feitravel.tw/blog/post/68753684",
              "style": "blue"
            }
          ]
        }
      ]
    },
    {
      "num": "10",
      "title": "Day 2 費用試算（2人）",
      "timeRange": "",
      "mapQuery": "",
      "blocks": [
        {
          "kind": "alert",
          "variant": "note",
          "text": "ℹ 手環押金 ₩20,000 離場退還，實際支出不含此項。門票建議用 KKday / Klook 預購省 ₩20,000 左右。"
        }
      ]
    },
    {
      "num": "11",
      "title": "Day 2 行前 Checklist",
      "timeRange": "",
      "mapQuery": "",
      "blocks": [
        {
          "kind": "checklist",
          "items": [
            "行前預購：KKday 或 Klook 購入水上樂園全日票，確認 QR Code 在手機可顯示，備份截圖。",
            "泳衣：男士泳褲、女士連身或兩件式泳衣，注意備有舒適的水上活動泳衣，不建議穿比基尼三角褲玩滑梯（容易走光）。",
            "毛巾：自帶一條大浴巾最省，否則現場租借需付費。",
            "夾腳拖 / 水鞋：水上樂園地面會燙，室外要穿。水鞋防滑更好。",
            "防曬乳：強烈建議高 SPF（50+），玩水後需補擦，準備防水型。",
            "防水手機袋：手環刷卡消費時需要看手機確認，要能在水邊使用。",
            "現金：帶 ₩30,000–50,000，計程車、手環押金用現金比較方便。",
            "換洗衣物＋護膚品：玩完要去吃晚餐，準備舒服的換洗衣物和乳液（玩水很乾燥）。",
            "Kakao T 事先安裝：出發前確認已安裝並綁定信用卡或支付方式。",
            "早餐吃好：玩水消耗體力，空腹不建議玩刺激設施。",
            "手機防水：若手機本身非防水，請務必裝入防水袋，水上樂園有大量水花。"
          ]
        }
      ]
    }
  ]
};

export default day2Plan;
