// AUTO-GENERATED by scripts/import-schedule.mjs — do not edit manually
import type { DayPlan } from '../types/dayPlan';

const day3Plan: DayPlan = {
  "day": 3,
  "title": "影島文化 → 西區串聯 → 入住海雲台",
  "subtitle": "退房＋Egg Drop早餐 → ARTE MUSEUM → 甘川洞 → 松島纜車 → 南浦洞採買 → 樂天超市 → 海雲台入住 → 海雲台市場晚餐",
  "tags": [
    "Pass 藍色 ×2（ARTE + 松島纜車）",
    "今日換住海雲台",
    "ZIM CARRY 行李宅配",
    "最長移動日"
  ],
  "timeline": [
    { "time": "08:30", "event": "Egg Drop 早餐", "dotColor": "gold" },
    { "time": "10:00", "event": "ARTE MUSEUM 影島", "dotColor": "accent" },
    { "time": "12:20", "event": "甘川洞文化村", "dotColor": "teal" },
    { "time": "13:20", "event": "松島海上纜車（水晶車廂）", "dotColor": "blue" },
    { "time": "14:30", "event": "南浦洞採買串聯", "dotColor": "accent" },
    { "time": "16:00", "event": "樂天超市光復店伴手禮大採買", "dotColor": "gold" },
    { "time": "18:00", "event": "海雲台飯店 Check-in", "dotColor": "teal" },
    { "time": "19:30", "event": "海雲台傳統市場晚餐", "dotColor": "accent" }
  ],
  "sections": [
    {
      "num": "01",
      "title": "退房 + 早餐：Egg Drop 西面店",
      "timeRange": "08:00–09:20",
      "blocks": [
        {
          "kind": "alert",
          "variant": "tip",
          "text": "**前一晚必做（ZIM CARRY 行李宅配）**：KKday 預訂 ZIM CARRY 行李宅配：西面飯店取件 → 金海機場 3F 送達。今天行程橫跨全城 5 個點，行李宅配是唯一讓你全程輕裝的方式。費用：每件 ₩15,000（24吋以上 +₩5,000）。退房時把行李交給飯店 Check-in 台，確認 ZIM CARRY 上午取件時間。**隨身小包備好**：Pass 卡、換洗衣物一套、充電器、重要證件，不要把當晚要用的東西全部放進托運行李。"
        },
        {
          "kind": "info-card",
          "variant": "gold",
          "rows": [
            {
              "label": "必點",
              "value": "**蒜香培根起司（Garlic Bacon Cheese）**₩5,400 — 大蒜吐司＋厚燒歐姆蛋＋培根＋起司，人氣 No.1。\n**美式火腿起司（American Ham Cheese）**₩4,900 — 口味較清淡，初次嘗試的好選擇。"
            },
            {
              "label": "建議點法",
              "value": "食量小的兩人：**各點一份三明治，共享一份薯餅**就夠。不需要點套餐，套餐量多容易撐到影響後續行程。"
            },
            {
              "label": "點餐方式",
              "value": "自助點餐機，右上角切換「中文」（大陸用語）或「English」（更直覺）。刷信用卡或 WOWPASS，收據號碼叫到再去領。"
            },
            {
              "label": "等待時間",
              "value": "平日早上約 10–20 分鐘，店內約 8–10 個座位，外帶站著吃很常見。"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "warn",
          "text": "菜單中文翻譯是大陸用語（「芝士」＝起司、「牛油果」＝酪梨），若看不懂建議切英文介面。「套餐」比「單點」多薯餅＋飲料，食量小的話直接單點三明治就好。"
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "退房後先把行李交給飯店（ZIM CARRY 上午取件），再輕鬆步行去吃早餐。今天是最長的移動日，早餐吃輕一點，留肚子給下午的各種小吃。"
        }
      ]
    },
    {
      "num": "02",
      "title": "西面 → ARTE MUSEUM（影島）",
      "timeRange": "09:20 出發",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "accent",
          "rows": [
            {
              "label": "交通",
              "value": "西面飯店 → ARTE MUSEUM，計程車約 **20 分鐘、₩12,000–15,000**"
            },
            {
              "label": "叫車韓文",
              "value": "(아르떼뮤지엄 부산)　或　(부산 영도구 해양로247번길 29)"
            },
            {
              "label": "ARTE 開門",
              "value": "10:00。建議 09:50 前到，趕第一批人場最清靜。"
            }
          ]
        },
        {
          "kind": "ticket",
          "text": "西面 → ARTE MUSEUM ｜ 計程車 ≈ ₩13,000 ｜ 約 20 分"
        }
      ]
    },
    {
      "num": "03",
      "title": "ARTE MUSEUM 釜山",
      "timeRange": "10:00–12:00｜停留約 2 小時",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "accent",
          "rows": [
            {
              "label": "地址",
              "value": "釜山廣域市影島區海洋路247番街29（아르떼뮤지엄 부산）"
            },
            {
              "label": "時間",
              "value": "10:00–19:00（最後入場 18:00）"
            },
            {
              "label": "Pass",
              "value": "原價 ₩22,000；Pass 藍色 #1 免費入場"
            },
            {
              "label": "建議",
              "value": "開館即入最清靜；停留 1.5–2 小時足夠"
            },
            {
              "label": "穿著",
              "value": "不要穿純白衣服，光影投射會讓白衣太搶鏡"
            }
          ]
        },
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "accent",
              "label": "①",
              "title": "出示 Pass 換票入場",
              "body": "售票口出示 Visit Busan Pass（藍色），換票入場。10:00 剛開門人最少，拍照不用搶位置。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "accent",
              "label": "②",
              "title": "四個必拍展廳",
              "body": "**花卉展廳**：地板反射花海，角蹲構圖最佳，人在花海中\n**瀑布廳**：水幕配動態光效，站在中央往上仰拍很壯觀\n**動態星空廳**：躺地板仰拍效果最佳，帶小外套鋪地比較舒服\n**無限鏡廳**：人在鏡中無限延伸，等沒有其他遊客入鏡的瞬間耐心拍",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "accent",
              "label": "③",
              "title": "12:00 出館，旁邊的 P.ARK 快速路過",
              "body": "ARTE 旁的文創空間 P.ARK 有幾間咖啡廳，可以路過看一眼。今天若肚子餓了，這裡是午餐備選方案之一（詳見附錄）。不特地停留，準時出發趕甘川洞。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            }
          ]
        },
        {
          "kind": "photo-ref",
          "label": "ARTE 必拍展廳位置 · Pass換票流程",
          "desc": "花卉廳角蹲拍法、瀑布廳人像位置、星空廳躺拍構圖、P.ARK 咖啡廳",
          "links": [
            { "text": "→ Pass 換票流程", "href": "#", "style": "default" },
            { "text": "→ 必拍角度整理", "href": "#", "style": "amber" }
          ]
        }
      ]
    },
    {
      "num": "04",
      "title": "ARTE → 甘川洞文化村",
      "timeRange": "12:00 出發 · 12:20–13:10（停留 55 分）",
      "blocks": [
        {
          "kind": "ticket",
          "text": "ARTE → 甘川洞文化村 ｜ 計程車 ≈ ₩6,000 ｜ 約 12–15 分"
        },
        {
          "kind": "info-card",
          "variant": "teal",
          "rows": [
            {
              "label": "叫車韓文",
              "value": "(감천문화마을 안내센터)"
            },
            {
              "label": "地址",
              "value": "釜山沙下區甘內2路203（遊客中心）"
            },
            {
              "label": "入村",
              "value": "免費，地圖＋小王子磁鐵紀念品組合 ₩2,000"
            },
            {
              "label": "策略",
              "value": "今天走馬看花 55 分鐘，主拍彩色階梯、小王子壁畫、全村俯瞰"
            }
          ]
        },
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "teal",
              "label": "①",
              "title": "遊客中心買地圖（₩2,000）",
              "body": "進村後先到遊客中心買地圖，上面標有所有必拍點位，讓你不會迷路走冤枉路。含小王子磁鐵當作紀念品也很合適。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "②",
              "title": "必拍三個點",
              "body": "**小王子壁畫**：最著名打卡點，對著蒼藍大海的小王子彩繪，廣場上拍\n**彩色階梯俯瞰**：從高處往下看滿村彩色房屋，代表性全景照\n**甘川洞全景最高點**：找視野最開闊位置，把整個村子＋海港一起入鏡",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "③",
              "title": "13:10 出村叫車",
              "body": "走馬看花不需全部走透透。下坡路出村，直接叫計程車前往松島纜車。**不能貪玩太久**，後面還有三個大點要跑。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "warn",
          "text": "甘川洞山路多、階梯多，今天行程全天步行量大，建議穿舒適的鞋。氣溫高時山坡曬得很厲害，帶遮陽帽或防曬。"
        }
      ]
    },
    {
      "num": "05",
      "title": "甘川洞 → 松島海上纜車（水晶車廂）",
      "timeRange": "13:10 出發 · 13:25–14:20（停留約 1 小時）",
      "blocks": [
        {
          "kind": "ticket",
          "text": "甘川洞 → 松島纜車 A 站 ｜ 計程車 ≈ ₩7,000 ｜ 約 12–15 分"
        },
        {
          "kind": "info-card",
          "variant": "blue",
          "rows": [
            {
              "label": "叫車韓文",
              "value": "(송도해상케이블카 / 부산 서구 송도해변로 171)"
            },
            {
              "label": "時間",
              "value": "09:00–22:00（冬季至 21:00）"
            },
            {
              "label": "Pass",
              "value": "水晶車廂原價 ₩22,000 / 人；Pass 藍色 #2 免費（指定換水晶車廂）"
            },
            {
              "label": "路線",
              "value": "A站（松島海水浴場端）出發；全程 1.8km，單趟約 10 分鐘"
            }
          ]
        },
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "blue",
              "label": "①",
              "title": "A 站售票口換票",
              "body": "1F 售票窗口出示 Pass 藍色換票，指定**水晶車廂（유리 캡슐 / Crystal Capsule）**。平日等候通常不超過 20 分鐘。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "blue",
              "label": "②",
              "title": "水晶車廂體驗",
              "body": "車廂底部全透明，腳下直接踩著大海，有懼高感的人要有心理準備！\n從 A 站出發往 B 站，沿途可欣賞松島海岸線全景。**請確認換票時含單程還是來回**——Pass 通常含單程，到 B 站後可搭返回的一般車廂或步行回 A 站。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "blue",
              "label": "③",
              "title": "松島龍宮空中步道（加選）",
              "body": "纜車下來後，附近的**松島龍宮雲橋**（空中步道）也是 Pass 免費景點，15 分鐘可走完，俯瞰效果不錯。今天時間較緊，可依狀況選擇要不要走。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "水晶車廂和一般車廂差很多——透明底部踩著海是最大亮點，一定要用 Pass 換水晶車廂。Pass 節省的 ₩44,000 就靠這兩個景點回本。"
        }
      ]
    },
    {
      "num": "06",
      "title": "松島 → 南浦洞採買串聯",
      "timeRange": "14:20 出發 · 14:30–15:50（停留約 1.5 小時）",
      "blocks": [
        {
          "kind": "ticket",
          "text": "松島 → 南浦洞 ｜ 計程車 ≈ ₩5,000 ｜ 約 10 分"
        },
        {
          "kind": "info-card",
          "variant": "accent",
          "rows": [
            {
              "label": "重點",
              "value": "南浦洞以**邊走邊吃的街頭小吃**為主，**不在這裡坐下來吃正餐**——主力採買留在後面樂天超市。"
            },
            {
              "label": "動線",
              "value": "BIFF 廣場黑糖餅 → 光復路隨意逛（Olive Young / 藥妝補貨）→ 步行至樂天超市光復店（約 5–8 分鐘）"
            }
          ]
        },
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "accent",
              "label": "①",
              "title": "BIFF 廣場：元祖黑糖餅",
              "body": "**元祖大叔黑糖餅（원조할아버지씨앗호떡）**人龍最長，黑糖蜂蜜口味 ₩1,500 一個，外脆內燙要小心咬。\n旁邊還有昇基堅果黑糖餅（堅果版），口感不同各買一個比較，食量小各吃一個就夠了，別買太多撐壞肚子。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "accent",
              "label": "②",
              "title": "光復路補貨（選）",
              "body": "Olive Young、藥妝店在光復路上很集中，有需要的話順手補充美妝、面膜。**主力採買留在樂天超市做**，這裡只是路過看看。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "accent",
              "label": "③",
              "title": "15:50 步行到樂天超市",
              "body": "南浦洞光復路往樂天超市光復店步行約 5–8 分鐘，不需叫車。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            }
          ]
        }
      ]
    },
    {
      "num": "07",
      "title": "樂天超市光復店（伴手禮大採買）",
      "timeRange": "16:00–17:30（停留約 1.5 小時）",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "gold",
          "rows": [
            {
              "label": "地址",
              "value": "釜山中區中區路59（南浦洞光復路旁步行可達）"
            },
            {
              "label": "時間",
              "value": "10:00–23:00（每月二、四週週一公休，出發前確認）"
            },
            {
              "label": "退稅",
              "value": "單筆消費滿 ₩15,000 可辦，結帳時出示護照申請 TAX FREE 退稅單"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "**樂天超市掃貨清單（食量小版本）：**\n**零食伴手禮（輕盈好帶）**：HBAF 杏仁果各口味（蜂蜜奶油、哇沙咪必入）、烏龜餅乾多口味組、辣炒年糕味餅乾、Binch 巧克力餅乾、蜂蜜貝果片（Olive Young 有，這裡也有）\n**泡麵（限帶得走的量）**：農心辣牛肉麵、辛拉麵黑色版、炸醬麵、釜山限定口味。注意：泡麵佔重量和體積，別買太多\n**生活小物**：韓系面膜（比 Olive Young 便宜一些）、牙貼、護手霜\n**液體類**（醬料、飲料）只能托運，不能帶手提上飛機。今天 ZIM CARRY 行李已送走，液體類請謹慎或找宅配服務"
        },
        {
          "kind": "alert",
          "variant": "warn",
          "text": "今天行李已 ZIM CARRY 送機場，不能臨時加東西進去！採買的東西要**自己隨身帶著去海雲台**。建議只買輕便好拿的，重的留 Day 5 前往機場前的最後機會再買。"
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "退稅建議在機場辦，比在現場辦更快。購物時請店員開立 **TAX FREE 退稅單**（非一般收據），保存好，回程機場退稅機掃描即可拿現金。"
        }
      ]
    },
    {
      "num": "08",
      "title": "南浦洞 → 海雲台 · 入住飯店",
      "timeRange": "17:30 出發 · 18:00–19:00",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "teal",
          "rows": [
            {
              "label": "交通",
              "value": "樂天超市光復店 → 海雲台飯店，計程車約 **35–40 分鐘、₩28,000–35,000**。走廣安大橋快約 10 分，加收 **₩1,000 橋費**（正常現象，跳表加入即可）。帶著採買袋不建議搭地鐵換線。"
            },
            {
              "label": "叫車目的地",
              "value": "直接輸入海雲台飯店韓文名稱，或 Uber 輸入中文地址。"
            },
            {
              "label": "入住",
              "value": "海雲台飯店通常 15:00 後可入住。抵達先辦 Check-in，整理好採買物品，輕裝出門吃晚餐。"
            }
          ]
        },
        {
          "kind": "ticket",
          "text": "南浦洞 → 海雲台飯店 ｜ 計程車 ≈ ₩32,000 ｜ 約 38 分（走廣安大橋）"
        },
        {
          "kind": "alert",
          "variant": "note",
          "text": "Check-in 後確認 ZIM CARRY 行李是否送達（通常 17:00–20:00 間送到）。若未到先盥洗梳妝，晚餐回來剛好可以拿行李整理。"
        }
      ]
    },
    {
      "num": "09",
      "title": "晚餐：海雲台傳統市場",
      "timeRange": "19:30–21:00",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "teal",
          "rows": [
            {
              "label": "交通",
              "value": "海雲台站 3 號出口，往海水浴場方向直走約 5 分鐘，左手邊"
            },
            {
              "label": "時間",
              "value": "各店家大約 10:00–24:00（攤販傍晚開始最熱鬧）"
            },
            {
              "label": "氛圍",
              "value": "傳統市場式晚餐，小吃＋正餐都有，在地人＋觀光客混合，氣氛熱鬧"
            }
          ]
        },
        {
          "kind": "menu",
          "header": "海雲台市場必吃選擇",
          "items": [
            { "name": "爐紅餃子刀切麵 (노홍만두칼국수)", "note": "市場內超過 60 年老店，蛤蜊刀切麵料多湯鮮，蝦仁蒸餃紮實好吃。蛤蜊刀切麵 ₩9,000｜蒸蝦餃 ₩5,000起" },
            { "name": "名品糖餅 (해운대명품호떡)", "note": "海雲台市場最著名小吃，5 種口味（蜂蜜/堅果/紅豆/黑糖/起司），長排隊代表好吃。₩2,000–2,500 / 個" },
            { "name": "尚國家飯捲 (상국이네떡볶이)", "note": "辣炒年糕＋飯捲＋炸物組合，市場招牌攤，便宜快速。辣炒年糕 ₩4,000起" },
            { "name": "黑芝麻拿鐵 (시장 입구 블루 카페)", "note": "市場入口附近藍色招牌咖啡廳，上層厚實黑芝麻鮮奶油＋下層咖啡，建議先不攪拌直接喝奶油層。₩4,800" }
          ]
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "食量小的兩人推薦：**爐紅餃子刀切麵一碗**（當正餐）→ 出來繞市場隨意逛 → **名品糖餅各一個**（甜點收尾）→ **黑芝麻拿鐵一杯**（散步邊喝）。三項合計約 ₩16,000–20,000 / 2人，輕鬆不撐。吃完步行到海雲台海灘吹海風，完美收尾第一個海雲台之夜。"
        },
        {
          "kind": "photo-ref",
          "label": "海雲台市場夜景 · 名品糖餅攤 · 刀切麵菜單",
          "desc": "市場入口夜間氛圍、名品糖餅排隊實況、爐紅餃子刀切麵菜單、黑芝麻拿鐵藍色咖啡廳",
          "links": [
            { "text": "→ 5家必吃地圖", "href": "https://whatime.space/haeundae-market/", "style": "default" },
            { "text": "→ 海雲台美食總整理", "href": "https://www.bigfang.tw/blog/post/busan-haeundae-delicioius", "style": "red" },
            { "text": "→ 糖餅對決＋芝麻拿鐵心得", "href": "https://blueberry1991.com/", "style": "amber" }
          ]
        }
      ]
    },
    {
      "num": "10",
      "title": "Day 3 費用試算（2人）",
      "timeRange": "",
      "blocks": [
        {
          "kind": "menu",
          "header": "費用明細",
          "items": [
            { "name": "Egg Drop 早餐（2人）", "note": "₩13,000 — 各一份三明治" },
            { "name": "ZIM CARRY 行李宅配", "note": "₩30,000 — 2件×₩15,000（前一晚預訂）" },
            { "name": "計程車 西面→ARTE", "note": "₩13,000 — 約 20 分" },
            { "name": "ARTE MUSEUM（2人）", "note": "₩0 — Pass 藍色 #1（原價 ₩44,000）" },
            { "name": "計程車 ARTE→甘川洞", "note": "₩6,000 — 約 13 分" },
            { "name": "甘川洞地圖×2（含磁鐵）", "note": "₩4,000 — 遊客中心購買" },
            { "name": "計程車 甘川洞→松島", "note": "₩7,000 — 約 13 分" },
            { "name": "松島水晶纜車（2人）", "note": "₩0 — Pass 藍色 #2（原價 ₩44,000）" },
            { "name": "計程車 松島→南浦洞", "note": "₩5,000 — 約 10 分" },
            { "name": "BIFF 黑糖餅 ×2", "note": "₩3,000 — 邊走邊吃" },
            { "name": "樂天超市採買（估）", "note": "₩60,000 — 零食伴手禮（可依需求增減）" },
            { "name": "計程車 南浦洞→海雲台", "note": "₩32,000 — 含橋費，約 38 分" },
            { "name": "海雲台市場晚餐（2人）", "note": "₩18,000 — 刀切麵＋糖餅＋芝麻拿鐵" },
            { "name": "合計（不含採買）", "note": "≈ ₩131,000 — 約 NT$2,900" },
            { "name": "Pass 今日省費（2人）", "note": "₩88,000 — ARTE ₩44,000 + 松島纜車 ₩44,000" }
          ]
        }
      ]
    },
    {
      "num": "11",
      "title": "Day 3 行前 Checklist",
      "timeRange": "",
      "blocks": [
        {
          "kind": "checklist",
          "items": [
            "**前一晚**：KKday 預訂 ZIM CARRY 行李宅配（西面飯店取件 → 金海機場 3F 送達）",
            "**Pass 確認**：Day 3 使用藍色 ×2（ARTE + 松島纜車），確認通行證有效",
            "**ARTE MUSEUM**：10:00 開門，建議 09:50 前到現場。不需預約，到現場出示 Pass 換票",
            "**松島纜車換票**：指定「水晶車廂（유리 캡슐）」，確認 Pass 含單程或來回",
            "**採買策略**：ZIM CARRY 行李已送機場，採買物品要隨身帶去海雲台。只買輕便的，重的留 Day 5 買",
            "**退稅單保存**：樂天超市結帳時出示護照，請店員開 TAX FREE 退稅單，保存到機場退稅",
            "**廣安大橋過橋費**：南浦洞→海雲台計程車走橋加 ₩1,000，正常現象不用糾結",
            "**ZIM CARRY 確認**：Check-in 後詢問飯店行李是否送達（通常 17:00–20:00）",
            "**海雲台市場晚餐**：爐紅餃子刀切麵＋名品糖餅，不用提前預約，現場排隊即可"
          ]
        },
        {
          "kind": "alert",
          "variant": "note",
          "text": "**附錄：午餐備選方案（依當下狀態選擇）：**\n**方案 A｜P.ARK 咖啡廳輕食（11:30 離開 ARTE 後）**：看完 ARTE 後直接去旁邊的 P.ARK 文創空間，有幾間咖啡廳和輕食店，坐下來吃個簡餐或甜點補能量，30–40 分鐘後出發。\n**方案 B｜甘川洞內邊走邊吃（12:20 逛村時）**：甘川洞遊客中心附近有章魚炸物、炒年糕、飯捲等小吃，邊逛邊吃，走馬看花同時解決肚子。\n**方案 C｜南浦洞商圈午餐（14:30 抵達後）**：南浦蔘雞湯（釜山觀光大使推薦的 30 年老店，一碗 ₩14,000）或老奶奶伽倻小麥冷麵（釜山在地冷麵代表），吃完再去樂天超市最順。"
        }
      ]
    }
  ]
};

export default day3Plan;
